
services:
   mongo:
     container_name: mongo
     image: mongo:5.0
     ports:
       - 27017:27017
     environment:
       MONGO_INITDB_ROOT_USERNAME: ynovdb
       MONGO_INITDB_ROOT_PASSWORD: passdb*2025#
     volumes:
       - ./storage:/data/db
     restart: always

   mongo-express:
     image: mongo-express:0.54
     ports:
       - 8081:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: ynovdb
       ME_CONFIG_MONGODB_ADMINPASSWORD: passdb*2025#
       ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
       ME_CONFIG_BASICAUTH_USERNAME: admin
       ME_CONFIG_BASICAUTH_PASSWORD: admin
     links:
       - "mongo"